### ISSUE TITLE
Run the project

### ISSUE THREAD

**Issue by michaelzfm** [zhihou7/BatchFormer#2]
Holle, I'm interested in your work for long-tailed problem, but could you tell me how to run the code? I can't find the code of the "encoder" in the RIDE folder.

**Comment by zhihou7** [comment]
Hi, 
Thanks for your interest.

Do you mean the file in ``https://github.com/zhihou7/BatchFormer/blob/main/long-tailed_recognition/RIDE-LongTailRecognition/model/fb_resnets/__init__.py" ?

**Comment by michaelzfm** [comment]
> 

Yes, thank you. So you have put it in your file , if I want to run RIDE+batchformer, just run the RIDE project in your file right?

**Comment by zhihou7** [comment]
Yes, Of course. All codes have included BatchFormer.

The encoder is just in https://github.com/zhihou7/BatchFormer/blob/3a0667b5c15d7410dfbb0de4c6c0bf10d836e4a3/long-tailed_recognition/RIDE-LongTailRecognition/model/fb_resnets/__init__.py#L12

You can run the experiment like,

      python train.py -c "configs/config_imagenet_lt_resnet10_ride.json" --reduce_dimension 1 --num_experts 3 --add_bt 1

You can disable BatchFormer with -add_bt 0.  I have updated the code and fixed a small typo right now.

Regards,
