### ISSUE TITLE
关于作者在将batchformerv2应用到deformable detr是否使用了deformable detr resnet50的预训练文件的问题

### ISSUE THREAD

**Issue by cbn3** [zhihou7/BatchFormer#23]

**Comment by cbn3** [comment]
作者你好，请问你在将batchformerv2应用到deformable detr是否使用了deformable detr resnet50的预训练文件？还是直接train from scratch

**Comment by zhihou7** [comment]
I train from scratch.

**Comment by cbn3** [comment]
> I train from scratch.

谢谢作者
