### ISSUE TITLE
batch_former_v2 issues

### ISSUE THREAD

**Issue by thisisqiaoqiao** [zhihou7/BatchFormer#29]
Hello, B in shape (B, N, C) in the picture represents Batchsize. If so, when batch_first= False of TransformerEncoderLayer, the input and output should be (seq, batch, feature), but your code input The size is (batch, seq, feature)

![image](https://github.com/zhihou7/BatchFormer/assets/127526922/eaa1de11-f5ae-4a4a-bbf6-48f56803b959)

**Comment by zhihou7** [comment]
We treat the seq as the batch dimension, then we apply the batchformer along the original batch dimension (the first dimension ).

**Comment by thisisqiaoqiao** [comment]
Thank you for your reply. Can you explain in detail the meaning of N and C in (B, N, C)? Does the V2 version have one more batch dimension than the original version? Thank you very much.

![image](https://github.com/zhihou7/BatchFormer/assets/127526922/82b02ed2-ec25-4f3f-a723-f7993664c79e)

**Comment by thisisqiaoqiao** [comment]
![image](https://github.com/zhihou7/BatchFormer/assets/127526922/6ac29c73-96b6-434d-b0e1-04b8e9e027ad)

**Comment by thisisqiaoqiao** [comment]
Is there a problem here?
![image](https://github.com/zhihou7/BatchFormer/assets/127526922/15b02134-9d7f-4e4e-bf15-770e5fb276bc)

**Comment by zhihou7** [comment]
It is right. N is the batch dimension. You will calculate bf along the first dimension.

**Comment by thisisqiaoqiao** [comment]
Thank you very much for your reply.
